/*
카테고리 종류
00 총류
01 철학
02 종교
03 사회과학
04 자연과학 
05 기술과학
06 예술
07 언어
08 문학
09 역사
https://www.bigdata-culture.kr/bigdata/user/data_market/detail.do?id=9bc56c9c-bc4e-4b68-90da-f4900009fc05
컬럼명 및 데이터 타입 참고
*/

DROP TABLE TB_BOOK;


CREATE TABLE TB_BOOK(
    REGIST_NO NUMBER PRIMARY KEY,
    TITLE_NM VARCHAR2(50) NOT NULL,
    AUTHOR_NM VARCHAR2(30) NOT NULL,
    PUBLISHER VARCHAR2(30) NOT NULL,
    PUBLISHER_DATE DATE NOT NULL,
    REGIST_DATE DATE DEFAULT SYSDATE,
    BOOK_CATEGORY VARCHAR2(30) CHECK(BOOK_CATEGORY IN ('총류', '철학', '종교', '사회과학', '자연과학', '기술과학', '예술', '언어', '문학', '역사')) NOT NULL,
    PRICE NUMBER NOT NULL
);


COMMENT ON COLUMN TB_BOOK.REGIST_NO IS '등록 번호';
COMMENT ON COLUMN TB_BOOK.TITLE_NM IS '제목명' ;
COMMENT ON COLUMN TB_BOOK.AUTHOR_NM IS '저자명' ;
COMMENT ON COLUMN TB_BOOK.PUBLISHER IS '출판사' ;
COMMENT ON COLUMN TB_BOOK.PUBLISHER_DATE IS '출판일' ;
COMMENT ON COLUMN TB_BOOK.REGIST_DATE IS '등록일' ;
COMMENT ON COLUMN TB_BOOK.BOOK_CATEGORY IS '서적 분류' ;
COMMENT ON COLUMN TB_BOOK.PRICE IS '가격' ;


DROP SEQUENCE SEQ_REGIST_NO;

CREATE SEQUENCE SEQ_REGIST_NO
NOCACHE;

INSERT INTO TB_BOOK
VALUES(SEQ_REGIST_NO.NEXTVAL, 'SQL초급 활용', '교육부', '정부', '2021-12-31', SYSDATE, '총류', 12000);
INSERT INTO TB_BOOK
VALUES(SEQ_REGIST_NO.NEXTVAL, 'SQL중급 활용', '교육부', '정부', '2022-01-02', SYSDATE, '총류', 15000);
INSERT INTO TB_BOOK
VALUES(SEQ_REGIST_NO.NEXTVAL, 'SQL고급 활용', '교육부', '정부', '2022-12-31', SYSDATE, '총류', 20000);
INSERT INTO TB_BOOK
VALUES(SEQ_REGIST_NO.NEXTVAL, '초보자를 위한 리액트 200제', '이정열', '정부문화사', '2020-12-31', SYSDATE, '총류', 25000);
INSERT INTO TB_BOOK
VALUES(SEQ_REGIST_NO.NEXTVAL, '루틴의 힘', '댄 에리얼리', '금강산출판', '2021-07-25', SYSDATE, '총류', 15000);
INSERT INTO TB_BOOK
VALUES(SEQ_REGIST_NO.NEXTVAL, '신곡(지옥편)', '단테', '민음사', '2021-01-23', SYSDATE, '문학', 18000);
INSERT INTO TB_BOOK
VALUES(SEQ_REGIST_NO.NEXTVAL, '신곡(연옥편)', '단테', '민음사', '2021-02-23', SYSDATE, '문학', 18000);
INSERT INTO TB_BOOK
VALUES(SEQ_REGIST_NO.NEXTVAL, '신곡(천국편)', '단테', '민음사', '2021-04-07', SYSDATE, '문학', 20000);


SELECT * FROM TB_BOOK;

COMMIT;